Fix packaging, REPL.
After some directory renaming, the final package was missing some jars.
Also, the REPL was not working after changes were made to stop using
fat jars.

To fix the REPL, I'm using a similar approach to that used by the local
client: copy the needed REPL jars to a repl-specific directory, and add
all jars to the Spark application using "--jars". The list of jars can
be configured so that they can point at cached locations (e.g. local: or
hdfs:).

Since setup-classpath was not useful for the livy-repl script, I inlined
it into livy-server; in fact, the livy-repl script is not used anywhere,
so maybe we could remove it.

diff --git a/bin/livy-repl b/bin/livy-repl
--- a/bin/livy-repl
+++ b/bin/livy-repl
@@ -29,10 +29,19 @@ else
 	SPARK_SUBMIT=spark-submit
 fi
 
-source ./bin/setup-classpath
+LIBDIR="$LIVY_HOME/repl-jars"
+if [ ! -d "$LIBDIR" ]; then
+  LIBDIR="$LIVY_HOME/repl/target/jars"
+fi
+if [ ! -d "$LIBDIR" ]; then
+  echo "Could not find Livy REPL jars directory." 1>&2
+  exit 1
+fi
 
+JARS=$(find $LIBDIR | paste -sd,)
 exec $SPARK_SUBMIT \
+  --jars "$JARS" \
 	--driver-java-options "$LIVY_REPL_JAVA_OPTS" \
 	--class com.cloudera.livy.repl.Main \
-	"$ASSEMBLY_JAR" \
+	"spark-internal" \
 	"$@"
diff --git a/bin/livy-server b/bin/livy-server
--- a/bin/livy-server
+++ b/bin/livy-server
@@ -23,7 +23,16 @@ set -e
 export LIVY_HOME=$(cd $(dirname $0)/.. && pwd)
 cd $LIVY_HOME
 
-source ./bin/setup-classpath
+LIBDIR="$LIVY_HOME/jars"
+if [ ! -d "$LIBDIR" ]; then
+  LIBDIR="$LIVY_HOME/assembly/target/jars"
+fi
+if [ ! -d "$LIBDIR" ]; then
+  echo "Could not find Livy jars directory." 1>&2
+  exit 1
+fi
+
+CLASSPATH="$LIBDIR/*:$LIVY_HOME/conf:$CLASSPATH"
 
 exec java \
 	$LIVY_SERVER_JAVA_OPTS \
