Generate a tarball for the Livy server.
The tarball contains all needed code to run Livy plus a separate
packaging for the local client, used to run the remote Spark
context; those jars are not yet used because we'll need to fix
a bug in the code.

Adjustments in the bin/ scripts were made (including removing
unneeded scripts), and a default logging config was added (to
avoid ugly messages during startup).

diff --git a/bin/setup-classpath b/bin/setup-classpath
--- a/bin/setup-classpath
+++ b/bin/setup-classpath
@@ -16,16 +16,13 @@
 # See the License for the specific language governing permissions and
 # limitations under the License.
 
-ASSEMBLY_DIR="$LIVY_HOME/livy-assembly/target/scala-2.10"
-
-for f in $ASSEMBLY_DIR/livy-assembly-*.jar; do
-	ASSEMBLY_JAR="$f"
-done
-
-if [[ ! -f "$ASSEMBLY_JAR" ]]; then
-	echo "failed to find $ASSEMBLY_JAR" 1>&2
-	echo "you need to build Livy before running this program" 1>&2
-	exit 1
+LIBDIR="$LIVY_HOME/jars"
+if [ ! -d "$LIBDIR" ]; then
+  LIBDIR="$LIVY_HOME/livy-assembly/target/jars"
+fi
+if [ ! -d "$LIBDIR" ]; then
+  echo "Could not find Livy jars directory." 1>&2
+  exit 1
 fi
 
-CLASSPATH="$ASSEMBLY_JAR:$CLASSPATH"
+CLASSPATH="$LIBDIR/*:$LIVY_HOME/conf:$CLASSPATH"
